server: 
   error:
      include-message: always
spring:
    datasource:
      url: jdbc:h2:mem:localdb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false
    main:
      allow-circular-references: true
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Spring Boot JWT
  jwt:
    client-id: ninjaone
    client-secret: ninjaonesecret
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: ninjaresourceid
          